title: Twinkal's Website
author: Twinkal Barai
email: your-email@domain.com
description: > Hi! Welcome to my website! My name is Twinkal and I am passionate about biology.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
