theme: minima

title: Twinkal's Website.
author: Twinkal Barai.
email: twinki376@gmail.com
description: > Hi! Welcome to my website! My name is Twinkal. I am passionate about biology...

# social links
instagram_username: @t_wklb
github_username: t3win

show_excerpts: true # set to false to remove excerpts on the homepage


